### ISSUE TITLE
Using HTML image tag as the first line of a post crashes app

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#411]
#### Expected behavior
I expect the post to show the image preview 

#### Actual behavior
App crashes.

#### How to reproduce
- Launch app
- Open the editor's page
- Start your post with with HTML image tag on the first line 
```
<img src="https://cdn.pixabay.com/photo/2018/02/23/22/48/light-3176887_1280.jpg">
```
- check the publish button!

***
* Browser/App version: eSteem Mobile V2
* Operating system: Android 8

#### Recording Of The Bug
<img src="https://i.ibb.co/N6Sf4L8/G-20190112-0232542.gif" alt="G-20190112-0232542" border="0">

**Comment by tobias-g1** [comment]
To add further information surrounding this issue:

I was able to replicate when logged in via SteemConnect, however not when I logged in via the eSteem method. Are you authenticating via SteemConnect too @horpeyloaded 

The following exception is provided:

```
2019-01-12 10:28:47.104 4553-4592/app.esteem.mobile E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: app.esteem.mobile, PID: 4553
    java.lang.ClassCastException: Value for message cannot be cast from ReadableNativeMap to String
        at com.facebook.react.bridge.ReadableNativeMap.checkInstance(ReadableNativeMap.java:148)
        at com.facebook.react.bridge.ReadableNativeMap.getNullableValue(ReadableNativeMap.java:140)
        at com.facebook.react.bridge.ReadableNativeMap.getString(ReadableNativeMap.java:190)
        at com.facebook.react.modules.dialog.DialogModule.showAlert(DialogModule.java:235)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:764)
```

Tested on Android 8.1.0
Application Version: 2.0.6
