### ISSUE TITLE
[BUG]; The app crashed after I searched my username and accessing it. 

### ISSUE THREAD

**Issue by HarryHeights** [esteemapp/esteem-mobile#680]
**Describe the bug**
The app crashed after I searched for my username, opened my profile from the search results, and clicked on my user after to access menu options. 

**To Reproduce**

1.  Search your username on the app.
2. Click on your username from the search results.
3. Click on your profile avatar

**Expected behavior**
I expected that even after I had performed the action of searching for my username and accessing my profile from it, I would still be able to navigate around the app without any error. 

**Screenshots or Video**
https://www.youtube.com/watch?v=sqfGgL2yI7I

**Test enviroment**
 - Device: Redmi Note 5 Pro
 - OS: Android 8.1
 - Software Version; Esteem mobile v2.0.9

**Additional context**
Here's the logcat I got from the crash

``` com.facebook.react.common.JavascriptException: s.props.navigation.openDrawer is not a function. (In 's.props.navigation.openDrawer()', 's.props.navigation.openDrawer' is undefined), stack:
_handleOpenDrawer@1523.js:1:410
onPress@1514.js:1:1282
touchableHandlePress@200.js:1:1256
_performSideEffectsForTransition@184.js:1:8619
_receiveSignal@184.js:1:7383
touchableHandleResponderRelease@184.js:1:4687
y@89.js:1:576
k@89.js:1:719
E@89.js:1:773
D@89.js:1:1940
F@89.js:1:2699
W@89.js:1:2499
<unknown>@89.js:1:14001
Ae@89.js:1:75072
ze@89.js:1:13671
Oe@89.js:1:13844
receiveTouches@89.js:1:14603
value@25.js:1:3311
<unknown>@25.js:1:822
value@25.js:1:2565
value@25.js:1:794

	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
	at android.os.Looper.loop(Looper.java:171)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by mistikk** [comment]
@HarryHeights I couldnt repreduce, can you test again?

**Comment by HarryHeights** [comment]
Okay. I will try it again

**Comment by HarryHeights** [comment]
I tested again and it is still reproducible.

**Comment by mistikk** [comment]
This issue has been solved in our latest update, can you check from below links and if it is okay for you or you have any feedback please let me know, thank you :) @HarryHeights 

iOS : install.appcenter.ms/orgs/esteem.app/apps/esteem-1/distribution_groups/internal
Android : install.appcenter.ms/orgs/esteem.app/apps/esteem/distribution_groups/internal

**Comment by HarryHeights** [comment]
Alright I'll check it out

**Comment by HarryHeights** [comment]
I've checked it out @mistikk

**Comment by mistikk** [comment]
@HarryHeights thanks :)
