### ISSUE TITLE
The app crashes when I click on the icon to check voters info or the reply button. This crash happens after I search a word and open one of the results. 

### ISSUE THREAD

**Issue by HarryHeights** [esteemapp/esteem-mobile#700]
**Describe the bug**
I already reported the issue about content of search results not showing. What I didn't know until recently is that clicking some icons would cause the app to crash. The icons are;

- Voters info list. 
- The reply button.

After I searched for a word and clicked on one of the results, the content didn't load. I clicked on any of those two buttons I listed above, and the app crashed. The weird thing is that both of them gave different logcat results. 

**To Reproduce**
After doing all the necessary steps to get into the app; 
1. Click on the search icon located at the top right of the app.
2. Type in a word in the search bar 
3. Click on any of the search results
4. The Page opens, but, content doesn't load
5. Click on any of these icons; Voters info, Reply button. Both of them are located at the bottom part of the app. 
6. See error. The app crashes when any of those buttons are clicked. 

**Expected behavior**
I had two expectations; 

*First expectation*
I expected that since the content of the page didn't load, the buttons on it would only be redundant, but won't cause the app to crash. 
*Second expectation*
I expected that, if I clicked on those buttons, they'll perform the action there were originally meant to perform and perhaps, forcibly cause the content of the page to load. 

**Screenshots or Video**
https://youtu.be/psUcWxUf5io

**Test Environment**
 - Device: Redmi Note 5 PRO
 - OS: Android 8.1
 - Software version: Esteem mobile 2.0.9

**Additional context**
Like I stated in the bug description, using any of those buttons gave different crash log results. 

This is the logcat from when I clicked the voters info button;

``` com.facebook.react.common.JavascriptException: null is not an object (evaluating 'E.active_votes'), stack:
onPress@1577.js:1:1251
onPress@1365.js:1:511
touchableHandlePress@303.js:1:1678
_performSideEffectsForTransition@184.js:1:8619
_receiveSignal@184.js:1:7383
touchableHandleResponderRelease@184.js:1:4687
y@89.js:1:576
k@89.js:1:719
E@89.js:1:773
D@89.js:1:1940
F@89.js:1:2699
W@89.js:1:2499
<unknown>@89.js:1:14001
Ae@89.js:1:75072
ze@89.js:1:13671
Oe@89.js:1:13844
receiveTouches@89.js:1:14603
value@25.js:1:3311
<unknown>@25.js:1:822
value@25.js:1:2565
value@25.js:1:794

	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
	at android.os.Looper.loop(Looper.java:171)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
	at java.lang.Thread.run(Thread.java:764)
```
This is the logcat when I clicked the reply post button;

```
com.facebook.react.common.JavascriptException: TypeError: TypeError: TypeError: null is not an object (evaluating 'V.summary')

This error is located at:
    in s
    in InjectIntl(s)
    in n
    in InjectIntl(n)
    in Connect(InjectIntl(n))
    in S
    in InjectIntl(S)
    in Connect(InjectIntl(S))
    in s
    in RCTView
    in f
    in C
    in n
    in E
    in RCTView
    in n
    in RCTView
    in H
    in L
    in RCTView
    in h
    in v
    in h
    in _
    in N
    in s
    in c
    in h
    in N
    in C
    in Connect(C)
    in IntlProvider
    in o
    in n
    in Connect(n)
    in l
    in Unknown
    in h
    in RCTView
    in RCTView
    in c

This error is located at:
    in N
    in s
    in c
    in h
    in N
    in C
    in Connect(C)
    in IntlProvider
    in o
    in n
    in Connect(n)
    in l
    in Unknown
    in h
    in RCTView
    in RCTView
    in c

This error is located at:
    in N
    in C
    in Connect(C)
    in IntlProvider
    in o
    in n
    in Connect(n)
    in l
    in Unknown
    in h
    in RCTView
    in RCTView
    in c, stack:
value@1449.js:1:3227
yr@89.js:1:45857
Jr@89.js:1:61660
Kr@89.js:1:62132
zi@89.js:1:69082
Ii@89.js:1:68425
Ae@89.js:1:75098
ze@89.js:1:13671
Oe@89.js:1:13844
receiveTouches@89.js:1:14603
value@25.js:1:3311
<unknown>@25.js:1:822
value@25.js:1:2565
value@25.js:1:794

	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
	at android.os.Looper.loop(Looper.java:171)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
	at java.lang.Thread.run(Thread.java:764)

**Comment by ue** [comment]
Fixed for IOS but not published for Android yet @feruzm
