### ISSUE TITLE
App crashed when I deleted the # sign deposited by clicking the Text template

### ISSUE THREAD

**Issue by cckole** [esteemapp/esteem-mobile#793]
### App info
Esteem
Version 2.0.9.  Still crashing in the updated version 2.1.0
https://github.com/esteemapp/esteem-mobile/issues/793

**Describe the bug**
Clicking on a text template (tT) and deleting it crashed the app

**To Reproduce**
1. Log into the app 
2. Click on the plus sign below
3. Click on the pencil icon to go to the editor
4. Click on the tT template beside the Italics icon on the editor.
5. Try to delete the # and note the crash

**Expected behavior**
I expected the # sign to be deleted wthout crashing the app

**Screenshots or Video**
https://youtu.be/m5rxHsQ62Zs

**Smartphone**
 - Device: [Techno spark K7]
 - OS: [Android 7.0]
 
## Logcat
```FATAL EXCEPTION: main
05-09 01:03:24.261   409   409 E AndroidRuntime: Process: app.esteem.mobile, PID: 409
05-09 01:03:24.261   409   409 E AndroidRuntime: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'selection' of a view managed by: AndroidTextInput
05-09 01:03:24.261   409   409 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:95)
05-09 01:03:24.261   409   409 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:132)
05-09 01:03:24.261   409   409 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:51)
05-09 01:03:24.261   409   409 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:32)
05-09 01:03:24.261   409   409 E AndroidRuntime: 	at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:138)
05-09 01:03:24.261   409   409 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute(UIViewOperationQueue.java:95)
05-09 01:03:24.261   409   409 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:894)
05-09 01:03:24.261   409   409 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1001)
05-09 01:03:24.261   409   409 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue.access$2400(UIViewOperationQueue.java:46)
05-09 01:03:24.261   409   409 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1061)
05-09 01:03:24.261   409   409 E AndroidRuntime: 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
05-09 01:03:24.261   409   409 E AndroidRuntime: 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:134)
05-09 01:03:24.261   409   409 E AndroidRuntime: 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:105)
05-09 01:03:24.261   409   409 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:915)
05-09 01:03:24.261   409   409 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:715)
05-09 01:03:24.261   409   409 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:647)
05-09 01:03:24.261   409   409 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:903)
05-09 01:03:24.261   409   409 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:836)
05-09 01:03:24.261   409   409 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:103)
05-09 01:03:24.261   409   409 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:203)
05-09 01:03:24.261   409   409 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6251)
05-09 01:03:24.261   409   409 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-09 01:03:24.261   409   409 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
05-09 01:03:24.261   409   409 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
05-09 01:03:24.261   409   409 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
05-09 01:03:24.261   409   409 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-09 01:03:24.261   409   409 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83)
05-09 01:03:24.261   409   409 E AndroidRuntime: 	... 23 more```

**Comment by mistikk** [comment]
It is fixed, you can test with next release (v2.1.1)
