### ISSUE TITLE
App crashed when I reblogged a post

### ISSUE THREAD

**Issue by cckole** [esteemapp/esteem-mobile#801]
**Describe the bug**
Esteem app crashed when I reblogged  a post

**To Reproduce**
After Login in to esteem app
1. Locate any post
2. Click on the three dots at the top right side of the post
3. Click on reblog and complete the action by clicking the reblog pop up below

**Expected behaviour**
My expectations was to see the post reblogged to my page on steemit.

**Screenshots or Video**
https://youtu.be/lOb55PQ2swg

**Smartphone**
 - Device: [Techno Spark K7]
 - OS: [Android 7.0]
 
**Project info**
- App Version : version.2.1.0

### logcat

```05-10 22:49:44.481 29274 29274 E AndroidRuntime: FATAL EXCEPTION: main
05-10 22:49:44.481 29274 29274 E AndroidRuntime: Process: app.esteem.mobile, PID: 29274
10 22:47:51.607   779   812 E BatteryStatsService: no controller energy info supplied
05-10 22:47:51.635   779   812 E BatteryStatsService: power: Missing API
05-10 22:47:51.656   779   812 E BatteryStatsService: modem info is invalid: ModemActivityInfo{ mTimestamp=0 mSleepTimeMs=0 mIdleTimeMs=0 mTxTimeMs[]=[0, 0, 0, 0, 0] mRxTimeMs=0 mEnergyUsed=0}
05-10 22:48:07.075  1225 18719 D SQLiteDatabase: beginTransaction()
05-10 22:48:07.078  1225 18719 D SQLiteDatabase: endTransaction()
05-10 22:48:30.714   223   223 E SurfaceFlinger: couldn't log to EventLog: Try again
05-10 22:48:30.714   223   223 E SurfaceFlinger: couldn't log to EventLog: Try again
05-10 22:48:30.714   223   223 E SurfaceFlinger: couldn't log to EventLog: Try again
05-10 22:48:30.714   223   223 E SurfaceFlinger: couldn't log to EventLog: Try again
05-10 22:48:30.714   223   223 E SurfaceFlinger: couldn't log to EventLog: Try again
05-10 22:48:30.714   223   223 E SurfaceFlinger: couldn't log to EventLog: Try again
05-10 22:48:30.714   223   223 E SurfaceFlinger: couldn't log to EventLog: Try again
05-10 22:48:43.761   779 28966 E Sensors : handleToDriver handle(0)
05-10 22:48:45.629   223   223 E SurfaceFlinger: couldn't log to EventLog: Try again
05-10 22:48:47.123   223   223 E SurfaceFlinger: couldn't log to EventLog: Try again
05-10 22:48:47.553 29782 29782 E ACRA    : Initializing ANR detector for process: com.facebook.services
05-10 22:48:47.749 29782 29782 E MPlugin : Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport
05-10 22:48:48.648   779 31472 E ActivityManager: Sending non-protected broadcast android.intent.action.ULTRA_POWER_MODE from system 29875:com.rlk.powersavemanagement/1000 pkg com.rlk.powersavemanagement
05-05-10 22:49:44.481 29274 29274 E AndroidRuntime: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'selection' of a view managed by: AndroidTextInput
05-10 22:49:44.481 29274 29274 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:95)
05-10 22:49:44.481 29274 29274 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:132)
05-10 22:49:44.481 29274 29274 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:51)
05-10 22:49:44.481 29274 29274 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:32)
05-10 22:49:44.481 29274 29274 E AndroidRuntime: 	at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:138)
05-10 22:49:44.481 29274 29274 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute(UIViewOperationQueue.java:95)
05-10 22:49:44.481 29274 29274 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:894)
05-10 22:49:44.481 29274 29274 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1001)
05-10 22:49:44.481 29274 29274 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue.access$2400(UIViewOperationQueue.java:46)
05-10 22:49:44.481 29274 29274 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1061)
05-10 22:49:44.481 29274 29274 E AndroidRuntime: 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
05-10 22:49:44.481 29274 29274 E AndroidRuntime: 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:134)
05-10 22:49:44.481 29274 29274 E AndroidRuntime: 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:105)
05-10 22:49:44.481 29274 29274 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:915)
05-10 22:49:44.481 29274 29274 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:715)
05-10 22:49:44.481 29274 29274 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:647)
05-10 22:49:44.481 29274 29274 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:903)
05-10 22:49:44.481 29274 29274 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:836)
05-10 22:49:44.481 29274 29274 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:103)
05-10 22:49:44.481 29274 29274 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:203)
05-10 22:49:44.481 29274 29274 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6251)
05-10 22:49:44.481 29274 29274 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-10 22:49:44.481 29274 29274 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
05-10 22:49:44.481 29274 29274 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
05-10 22:49:44.481 29274 29274 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
05-10 22:49:44.481 29274 29274 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-10 22:49:44.481 29274 29274 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83)
05-10 22:49:44.481 29274 29274 E AndroidRuntime: 	... 23 more
05-10 22:49:44.481 29274 29274 E AndroidRuntime: Caused by: java.lang.IndexOutOfBoundsException: setSpan (109 ... 109) ends beyond length 108
05-10 22:49:44.481 29274 29274 E AndroidRuntime: 	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1283)
05-10 22:49:44.481 29274 29274 E AndroidRuntime: 	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:699)
05-10 22:49:44.481 29274 29274 E AndroidRuntime: 	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:692)
05-10 22:49:44.481 29274 29274 E AndroidRuntime: 	at android.text.Selection.setSelection(Selection.java:76)
05-10 22:49:44.481 29274 29274 E AndroidRuntime: 	at android.widget.EditText.setSelection(EditText.java:102)
05-10 22:49:44.481 29274 29274 E AndroidRuntime: 	at com.facebook.react.views.textinput.ReactEditText.setSelection(ReactEditText.java:250)
05-10 22:49:44.481 29274 29274 E AndroidRuntime: 	at com.facebook.react.views.textinput.ReactTextInputManager.setSelection(ReactTextInputManager.java:278)
05-10 22:49:44.481 29274 29274 E AndroidRuntime: 	... 25 more```

**Comment by mistikk** [comment]
@cckole it is fixed, can you test again?

**Comment by cckole** [comment]
Yes, its now working fine. Thanks..
