### ISSUE TITLE
Esteem mobile v2.1 crashes when I access the esteem rewards page after launch. Before the security system becomes active. 

### ISSUE THREAD

**Issue by HarryHeights** [esteemapp/esteem-mobile#809]
**Describe the bug**
There's a tiny window when I launch the app which allows me quickly access a menu on the app before the security system kicks in. This window allowed me to get into the esteem points/rewards page. While I was on that page, the security protocol kicked in but caused the app to crash. 

**To Reproduce**

To reproduce the bug, you have to be fast and precise.

1. Launch the app
2. There's a tiny window before the app's security kicks in
3. In that window, access the steem rewards page which is the first icon after the plus (+) sign.
4. Stay on that page until the security system kicks in
5. See error. 

**Expected behavior**
In the previous version, this tiny window where I could access some menus before the security system of the app kicks in, when it did, the app didn't crash. That was what I expected in this case. 

**Screenshots or Video**
https://youtu.be/Q87P41QuSCg

**Test Environment:**
 - Device: Redmi Note 5 Pro
 - OS: Android 8.1
 - Version: Esteem mobile v2,1

**Logcat**
``` java.lang.ClassCastException: Value for title cannot be cast from ReadableNativeMap to String
at com.facebook.react.bridge.ReadableNativeMap.checkInstance(ReadableNativeMap.java:148)
at com.facebook.react.bridge.ReadableNativeMap.getNullableValue(ReadableNativeMap.java:140)
at com.facebook.react.bridge.ReadableNativeMap.getString(ReadableNativeMap.java:190)
at com.facebook.react.modules.dialog.DialogModule.showAlert(DialogModule.java:232)
at java.lang.reflect.Method.invoke(Native Method)
at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
at android.os.Handler.handleCallback(Handler.java:794)
at android.os.Handler.dispatchMessage(Handler.java:99)
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
at android.os.Looper.loop(Looper.java:176)
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
at java.lang.Thread.run(Thread.java:764)

```

**Comment by mistikk** [comment]
@HarryHeights it is fixed, can you test again?
