### ISSUE TITLE
Esteem mobile v2,1; The app crashed when I clicked on my profile avatar after accessing it from a link to my profile. 

### ISSUE THREAD

**Issue by HarryHeights** [esteemapp/esteem-mobile#810]
**Describe the bug**
When I open any page on the app that contains my username, clicking on it(my username) would open up my profile.  When on my profile, if I click on my profile avatar, the app crashes.

**To Reproduce**

1. Open a page which contains a link back to your profile.  It could be your own post.
2. When you open your post, click on your avatar on the page.
3. When your profile opens up, click on your profile avatar

**Expected behavior**
I expected that when I clicked on my profile avatar after accessing my profile from wherever, the left sliding menu would pop-up. 

**Screenshots or Video**
https://youtu.be/GpK9u23ABXA

**Smartphone (please complete the following information):**
 - Device: Redmi Note 5 Pro
 - OS: Android 8.1
 - Version: Esteem mobile v2.1

**Logcat**

``` com.facebook.react.bridge.NoSuchKeyException: lineNumber
at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:122)
at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:126)
at com.facebook.react.bridge.ReadableNativeMap.getInt(ReadableNativeMap.java:180)
at com.facebook.react.util.JSStackTrace.format(JSStackTrace.java:28)
at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
at java.lang.reflect.Method.invoke(Native Method)
at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
at android.os.Handler.handleCallback(Handler.java:794)
at android.os.Handler.dispatchMessage(Handler.java:99)
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
at android.os.Looper.loop(Looper.java:176)
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
at java.lang.Thread.run(Thread.java:764)

```

**Comment by ue** [comment]
@HarryHeights fixed
