### ISSUE TITLE
eSteem v2.1.0; I get a message 'The post was removed by you' when I open a push notifcation. If I try some other options, the app crashes. 

### ISSUE THREAD

**Issue by HarryHeights** [esteemapp/esteem-mobile#892]
**Describe the bug**
I received a push notification. I wanted more details so I clicked on the notification to open the app.  But when I did, I got a message that 'The post was removed by me'. However, I saw the 3 dots button on the page which means more options.  I tried the reblog option and the app crashed. The 'copy link' option also caused the app to crash. 

**To Reproduce**
To reproduce the bug, you need to get a notification. It could be natural or enforced. 
1. Click on the push notification 
2. Enter security pin
3. See error message 'The post was removed by you(your username)
4. Click on the 3 dots by the side
5. Select 'copy link' or 'reblog' option
6. See error. 

**Expected behavior**
I expected to see the content or action that I was notified of. 

**Screenshots or Video**
https://youtu.be/fAUA8qri5uQ

**Test Environment:**
 - Device: Redmi Note 5 Pro
 - OS: Android 8.1.0
 - Software version: eSteem v2.1.

**Logcat**

```  com.facebook.react.bridge.NoSuchKeyException: lineNumber
	at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:122)
	at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:126)
	at com.facebook.react.bridge.ReadableNativeMap.getInt(ReadableNativeMap.java:180)
	at com.facebook.react.util.JSStackTrace.format(JSStackTrace.java:28)
	at com.facebook.react.modules.core.ExceptionsManagerModule.reportSoftException(ExceptionsManagerModule.java:46)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:794)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
	at android.os.Looper.loop(Looper.java:176)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by ue** [comment]
Fixed @HarryHeights  wait new release please. thanx for report.
